In [1]:
from data import data, data_benchmark
from functions import AssetAllocation

[*********************100%%**********************]  70 of 70 completed
[*********************100%%**********************]  1 of 1 completed

In [2]:
data.head(3)

,AA,AAPL,ADI,ADSK,AFL,AMAT,AMD,ANF,APA,APH,...,PSA,R,RL,SEE,STX,SWK,TEL,TER,VLO,WAT
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-02,20.966393,73.152657,111.776886,187.830002,48.241650,59.824524,49.099998,17.227215,23.826841,52.450294,...,177.872101,47.104984,110.012260,36.397270,51.156189,151.720749,90.070976,68.510788,79.049683,235.059998
2020-01-03,21.044695,72.441452,109.809219,184.949997,47.907093,58.872337,48.599998,17.128660,24.136889,51.902885,...,179.790298,46.706142,109.428825,35.826069,49.811752,150.908066,89.007027,67.085121,76.049889,231.009995
2020-01-06,20.555285,73.018700,108.519073,187.119995,47.771446,57.602757,48.389999,17.010397,24.089912,51.633980,...,180.429703,46.558758,110.956902,35.545158,49.219864,150.366257,88.391052,65.629959,76.058189,228.880005

In [3]:
data_benchmark.head(3)

Date
2020-01-02    305.058441
2020-01-03    302.748444
2020-01-06    303.903442
Name: Adj Close, dtype: float64

In [4]:
AA=AssetAllocation(data_stocks=data, data_benchmark=data_benchmark, rf=.0525)

In [9]:
AA.sharpe_ratio(n_sims=10000)

array([0.00073107, 0.02816733, 0.02111483, 0.02351234, 0.00442146,
       0.02298748, 0.02710527, 0.02123732, 0.00723623, 0.00651537,
       0.00075603, 0.01769687, 0.00691041, 0.00425716, 0.00325511,
       0.01098686, 0.02497221, 0.00135514, 0.017056  , 0.01497766,
       0.02283288, 0.0041697 , 0.00148571, 0.00195548, 0.00078096,
       0.00896326, 0.01901831, 0.02412717, 0.01640223, 0.00459157,
       0.01623809, 0.00082089, 0.00691258, 0.01729055, 0.01980755,
       0.00986281, 0.01851082, 0.02468135, 0.00283031, 0.01868704,
       0.01456419, 0.01334976, 0.01224065, 0.00835497, 0.01822844,
       0.00766973, 0.02488525, 0.01520447, 0.00412738, 0.01325561,
       0.02113839, 0.01482876, 0.01481495, 0.01461392, 0.02704553,
       0.02140711, 0.01667481, 0.01911313, 0.00706004, 0.0067323 ,
       0.02079428, 0.02639156, 0.02737745, 0.01619264, 0.02795885,
       0.00310968, 0.02395724, 0.02444432, 0.01941339, 0.0098298 ])

In [10]:
AA.semivariance(n_sims=10000)

array([0.00116781, 0.01474065, 0.00615494, 0.01878299, 0.00121848,
       0.02847124, 0.02321162, 0.00787778, 0.01451088, 0.02835486,
       0.02907412, 0.02623078, 0.01064143, 0.02719985, 0.00115161,
       0.00339153, 0.02909255, 0.02765393, 0.00880988, 0.01648252,
       0.0053362 , 0.01762714, 0.00306605, 0.03029897, 0.00855803,
       0.01989932, 0.0168482 , 0.02395784, 0.01227124, 0.0075766 ,
       0.00673873, 0.02237749, 0.0276106 , 0.01774508, 0.002713  ,
       0.02831763, 0.00840946, 0.01380914, 0.00281408, 0.0055034 ,
       0.000821  , 0.00379515, 0.01741879, 0.00645513, 0.00772782,
       0.00573093, 0.02648169, 0.01282564, 0.00822092, 0.01200737,
       0.00412988, 0.02056428, 0.02236314, 0.0009075 , 0.02987637,
       0.01623101, 0.01824899, 0.00472379, 0.02627448, 0.02712923,
       0.01912453, 0.02674073, 0.00106306, 0.00435556, 0.01663348,
       0.01740942, 0.02264196, 0.00558675, 0.00141076, 0.007403  ])